### ISSUE TITLE
Forum Permissions changed in IPB 3

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#10]
So, I'm leary as it is to use beta converters because I was screwed over in the past by incomplete converters... but I decided to give this a go.

I'm using the IPB 3 (beta) converter and I've successfully converted: Usergroups, Users, Forums, & Threads. When I go to 'merge' Forum Permissions however, I get the following error:

MyBB has experienced an internal SQL error and cannot continue.
SQL Error:
1054 - Unknown column 'permission_array' in 'field list'
Query:
SELECT permission_array,id FROM ibf_forums LIMIT 0, 1000

The version of IPB I'm using is 3.2.1 which is not the latest (haven't reactivated my license because I plan on switching to MyBB in the future and just doing a pre-check for the conversion right now.

P.S. I'm pretty sure I'm using the HEAD version, but I could be wrong. The version number on the merge system didn't appear to update when I uploaded the HEAD version.

http://dev.mybb.com/issues/1857

**Comment by JN-Jones** [comment]
I can confirm that `permission_array` was removed, however I wasn't able to find how they replaced it. I've deactivated the forum permissions module for now

**Comment by JN-Jones** [comment]
Ok, I think I figured this out. Adding to 1.8.2
