### ISSUE TITLE
get_group_id is... wrong

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#101]
This function is a little bit confusing and sometimes useless.

From the description: `Convert a [board] group ID into a MyBB group ID`. There are easier ways to do this, I'll introduce a better method while fixing the forumpermissions module. However there's more:

The parameters for bbPress and phpBB: `get_group_id($uid, $options=array())`. So it selects all groups for `$uid` and converts them to the new ones and returns them as comma seperated list. `$options` can have two settings: `not_multiple` and `original` (last not supported by bbPress).
The issues here: `not_multiple` doesn't make any sense (example queries, but you should get the trick):

``` php
$query = $db->simple_select("users", COUNT(*) as rows, "uid=$uid");
$limit = $db->fetch_field($query, "rows");
$query = $db->simple_select("users", "*", "uid=$uid", array("limit_start => 1, "limit" => $limit);
```

what? fetch the number of rows a query would get and then execute the same query with a limit?
`original` doesn't make any sense too or at least it's too complicated. Also I'm not sure whether it's used anywhere.

Ok, that's already a lot to fix, however it becomes even better: IPB3, MyBB, PunBB, SMF 1 & 2 and vB4 have `$gid` instead of `$uid` as first parameter. They do what the description say: `$gid` in, new gid out. But why on earth do they have still the `$options` parameter? MyBB module:

``` php
        if($options['not_multiple'] == false)
        {
            $query = $this->old_db->simple_select("usergroups", "COUNT(*) as rows", "gid='{$gid}'");
            $settings = array('limit_start' => '1', 'limit' => $this->old_db->fetch_field($query, 'rows'));
            $this->old_db->free_result($query);
        }

        $query = $this->old_db->simple_select("usergroups", "*", "gid='{$gid}'", $settings);

        if(!$query)
        {
            return MYBB_REGISTERED;
        }

        $groups = array();
        while($mybbgroup = $this->old_db->fetch_array($query))
        {
            if($options['original'] == true)
            {
                $groups[] = $mybbgroup['gid'];
            }
            else
            {
                $groups[] = $this->get_gid($mybbgroup['gid']);
            }
        }

        $this->old_db->free_result($query);
        return implode(',', array_unique($groups));
```

That's A LOT of useless code.

And the SMF modules don't have the `$options` but they have to more parameters: `get_group_id($group_id, $is_group_row=false, $is_activated=1)`.

Here are my suggestions to fix all of the things:
As I'll add a short and easy method for getting the new usergroup we should use that for single usergroups (eg MyBB -> MyBB usergroup) and modify the `get_group_id` to accept the following parameters:
- `$id` -> contains either a single uid or an array of gids (if uid: select the gids)
- remove the `not_multiple` parameter
- check whether we really need the `original` parameter and if so return the original id's BEFORE we run any query
- check why SMF needs those parameters and look whether the function can detect that itself

**Comment by JN-Jones** [comment]
Postpointing as it works atm

**Comment by JN-Jones** [comment]
Ok, I was wrong above: it doesn't work (but it throws no errors). Additional groups aren't merged at all. Some boards even add users to the completly wrong usergroup.

**Comment by Sama34** [comment]
> I'm not sure whether it's used anywhere.

Someone probably suggested it to use it in private converters long ago. I believe much code was for that purpose.

**Comment by JN-Jones** [comment]
The comment was just about the original paramater - if it's set the function simply returns exactly the same gids that are used as parameters. The only thing some of the functions do if the original parameter is set is imploding an array. Also there's no need for us to support other modules that we're not supporting. I likely broke most of them anyways as I've changed already a lot of things.

**Comment by JN-Jones** [comment]
This is fixed now. `get_group_id` was moved to the main board class as it's the same for all boards except bbPress; all parameters were useless and therefor removed.
