### ISSUE TITLE
 SMF 2.0.1 Forum Permissions Fail

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#11]
When trying to merge forum permissions with SMF 2.0.1 it stands still. I was able to turn on error reporting for this one to get the message:

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 1000' at line 5
Query:
SELECT id_group, GROUP_CONCAT(permission) as permissions FROM smf_board_permissions WHERE id_group != '-1' GROUP BY id_group LIMIT , 1000

http://dev.mybb.com/issues/1851

**Comment by JN-Jones** [comment]
I'll close this as we need to rewrite the module anyways: #44
