### ISSUE TITLE
 SMF 2.0.1 Merging PMs Fail

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#12]
When trying to to merge pms from an smf 2.0.1 forum it gets stuck before finishing.

http://dev.mybb.com/issues/1850

**Comment by JN-Jones** [comment]
This is caused by pms with more than one recipient, they call an extra function which doesn't unset import_pmid. I'll fix this later today.

**Comment by JN-Jones** [comment]
Seems like [my fix](http://community.mybb.com/thread-155030-post-1081360.html#pid1081360) isn't working so I'll defer it for now.
