### ISSUE TITLE
column length is different than in the merged board

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#123]
I had this issue now multiple times for different boards and columns. Some examples:
vb saves the ICQ number as `char(20)` (and they don't check the input) while we save it as `varchar(10)` so if an user has entered something with more than 10 characters it'll throw an error.
The post message is `mediumtext` for them while ours is `text` which will throw an error too.

I've added a `substr` everywhere I saw the error, but this may happen everywhere so we should probably add a more general check. I thought about adding a new array to the modules with `column_name` => `length` (or modifying the existing default values array) and then modifying the `prepare_insert_array` function to run substr on the values.
@PirataNervo @Stefan-ST @Sama34 @JovanJ

**Comment by Sama34** [comment]
Your solution sounds feasible, maybe log all changes too (amount of occurrences)?

**Comment by JN-Jones** [comment]
It's not worth to log things, the log is already very big, more than 100 entries after a normal merge.

**Comment by Sama34** [comment]
How is the user suppose to know there were some issues with their content then? I meant something like:

> There were X occurrences that weren't successfully converted. Please read here for more information.

Or something, just so the user knows what happened and why (linking to a docs page).

**Comment by JN-Jones** [comment]
The cleanup page says already "check everything". We'd need another counter and we'd need more checks - my suggestion would simply run substr on every string. And most (valid) values shouldn't be modified (eg an ICQ number has always 9 numbers, so a valid one is never changed, only invalid ones with more than 10 chars are cut off)

**Comment by JN-Jones** [comment]
Probably we can determine the length of the field automatically and describe in the docs how to increase it? Or probably increase it dynamically? Not sure whether that works and whether it's fast enough though.

**Comment by Sama34** [comment]
What about adding the information to the module info as you suggested and then add an feature the user to increase the length of the field, so it will be their decision.

**Comment by JN-Jones** [comment]
I don't like the idea about informing the user about all columns - this would require a lot of changes and new overhead. We should either ignore the user and change the values directly (like I'm doing it atm) or dynamically modify those fields. Nothing which requires user interaction.

**Comment by JN-Jones** [comment]
New suggestion :P
Add a complete new module after the db configuration (or integrate it to the db one). Every "board" file contains an array with tables/columns which need to be checked (where the column length is greater than ours). The module would go through all of them, query the longest value (should be possible with something like `select length(col) where max(length(col))`) and then change our column definition to the new length. So the "real" modules don't need to worry about the values and we can simply work on them. Any thoughts?

**Comment by Sama34** [comment]
Sounds good, but wouldn't that affect for support? I mean, do we support "custom" DB schema changes? I'm not sure. But again, sounds fine to me.

**Comment by JN-Jones** [comment]
You're right, changing the database would probably cause issues on upgrades... -.-
Next one: same as above, new module which checks the fields, points out that their value can't be merged, linking to a docs page with more infos (what will happen with the value, how to increase the length of the field etc). Then add an array to the modules like I suggested first with the length of the field (if it's not possible to determine the length of the field)

**Comment by Sama34** [comment]
I think that sounds good. I'm not that famialirized with the merge system so I don't know that good |:

**Comment by JN-Jones** [comment]
Deferring

**Comment by JN-Jones** [comment]
Any other opinions before I start with this? @euantorano @Destroy666x

**Comment by JN-Jones** [comment]
Started with this in a seperate branch.

**Comment by euantorano** [comment]
> Next one: same as above, new module which checks the fields, points out that their value can't be merged, linking to a docs page with more infos (what will happen with the value, how to increase the length of the field etc). Then add an array to the modules like I suggested first with the length of the field (if it's not possible to determine the length of the field)

Sounds like the best solution. The docs page should make clear the potential issues of changing the field length too. It should also be made clear that the values will need re-inserting/updating once the column is manually changed.

**Comment by Destroy666x** [comment]
>  It should also be made clear that the values will need re-inserting/updating once the column is manually changed.

Yep. Otherwise there would be no point.

**Comment by Sama34** [comment]
I may be mixing things but I think the column should be changed before the script is executed.

**Comment by JN-Jones** [comment]
Exactly. That module would be run directly after we connected to the database so before anything gets inserted. And of course it'd point out possible issues ;)

**Comment by JN-Jones** [comment]
So, the basic functions have been added. Note that I haven't tested it with large databases. Mainly the output needs to be formatted now. If anyone has anything to mention feel free to do so before.

**Comment by JN-Jones** [comment]
Docs page @euantorano @Destroy666x @Sama34 http://docs.mybb.com/1.8/merge/column-length-check/

**Comment by JN-Jones** [comment]
Finished this. Still need to test it with my test databases but the error notice seems to work as it should.

**Comment by Sama34** [comment]
The doc page seems fine.

**Comment by euantorano** [comment]
Could we add a screenshot of the error page to the docs possibly? Might help users in some cases. Otherwise, everything looks good to me.

**Comment by JN-Jones** [comment]
There wasn't an error page when I wrote the page :P But yeah, will include one after I've tested it on one of my Big Boards.

**Comment by JN-Jones** [comment]
Added the screenshot

**Comment by JN-Jones** [comment]
Fixed the issues I've noticed while testing and merged this.
