### ISSUE TITLE
Improve BBCode Parser

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#138]
There are several issues with the current Parsers, espacially for those boards who use HTML (IPB).

We should: create an empty parser in "resources" (eg for MyBB or WBB where the BBCode is the same), create a HTML parser which parses HTML -> BBCode. Add a new variable to the board classes which indicates whether the empty, the html or a custom parser is used. And then fix the custom parsers.

**Comment by Sama34** [comment]
Why convert HTML -> BBCode? If HTML was allowed in the source forum it probably will in the end one.

**Comment by euantorano** [comment]
Some boards (IPB) seem to store the HTML no matter what.

**Comment by JN-Jones** [comment]
IPB (at least 4) and vanilla do that. Also there are some guys who believe allowing HTML can cause security issues (though we filter most malicious content).
