### ISSUE TITLE
Add avatar module

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#140]
There are some codes in different users modules which try to copy the users avatar however none of them copies the avatar file itself. We shouldn't do that in the users module itself so we need to write a complete new module which updates the user avatars and copies there files (if needed, there are also softwares which support gravatar and/or external URLs)

**Comment by JN-Jones** [comment]
We decided to defer the development of this module, however the existing codes will be removed in 1.8.1

**Comment by JN-Jones** [comment]
Work on this has started in the [fix-140-avatars_module](https://github.com/mybb/merge-system/tree/fix-140-avatars_module) branch. Keeping this out of feature for now as this may take some time and I want to be able to release 1.8.6 even without this.

**Comment by Sama34** [comment]
@Sama34
