### ISSUE TITLE
[IPB4] Polls aren't merged

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#152]
Running the polls module throws two warning (for both `foreach` loops) and doesn't merge the poll. After fixing this, the poll votes module needs to be checked too as it's likely not working too.

**Comment by EvilDragon** [comment]
Doesn't seem to be fixed for me :(
I confirmed that I'm using the fixed version, but I also get foreach-errors (the merger continues too fast as I could check the exact error message).
After that, the merger continues with 0 of 0 polls to import and finishes.

Poll votes of course doesn't work as no polls have been imported.

Using IPB 4.0.13

**Comment by JN-Jones** [comment]
Hi,

please use our forum for support. You can get the exact error message(s) by uploading https://github.com/JN-Jones/Merge-Log-Viewer which adds a new module to your MyBB ACP.
