### ISSUE TITLE
lastactive and lastvisit can be "0"

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#154]
Empty values (like "0" and "") are used by some boards as "Was never online", however MyBB shows it as "Less than 1 minute ago". The fields should default to the time of the merge if they're not available.

**Comment by Stefan-MyBB** [comment]
@JN-Jones Why not changing it to the registration date?

**Comment by JN-Jones** [comment]
Dylan defaulted to TIME_NOW everywhere (poll creation dates, poll votes and so on) so I simply did it as its done everywhere else. Though I agree, I'd create another issue for that and change it everywhere than having it different in some modules.
