### ISSUE TITLE
Merge System doesn't work with MyBB 1.8.4

### ISSUE THREAD

**Issue by ATofighi** [mybb/merge-system#158]
``` error
Fatal error: Interface 'DB_Base' not found in D:\xampp\htdocs\mybbmerge\inc\db_mysqli.php on line 12
```

**Comment by JN-Jones** [comment]
Ah, @euantorano changes. We need to fix the 1.8.3 package, the version here on GitHub is already modified but isn't release ready due some incomplete fixes.

**Comment by euantorano** [comment]
Yep, my fault. Sorry! :wink:

**Comment by ATofighi** [comment]
:)
If we don't want to change merge-system we can change the db_***.php files

**Comment by JN-Jones** [comment]
They're included in the mybb package so that isn't an option. We simply need to release merge system 1.8.4 based on the 1.8.3 package, fixing this issue and changing the version info.

**Comment by ATofighi** [comment]
@JN-Jones we can only add 

``` php
require_once MYBB_ROOT."inc/db_base.php";
```

 to `inc/db_mysql.php` and `inc/db_mysqli.php` and don't release new merge-system! :)

**Comment by JN-Jones** [comment]
Thats something @euantorano needs to decide as he was the one writing the base class.

**Comment by euantorano** [comment]
I'd say it's better to edit the merge system. IMO the class files should contain only the classes, nothing else. This is a standard convention in PHP.

**Comment by Sama34** [comment]
Even if the change is minimal a new version should be released.

**Comment by JN-Jones** [comment]
There's no discussion about **whether** this should be fixed, only about **how** and **where**?

**Comment by Sama34** [comment]
Per @ATofighi comments I understand he suggest to change the package only t oa minimum without marking a new release.

His fix looks good to me anyways. I seems to be backwards compatible.
