### ISSUE TITLE
 IPB, posthash + attachments

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#16]
t makes no sense to overwrite the variable some lines later: (boards/ipb2/attachments.php)

``` php
        $posthash = $this->get_import->post_attachment_details($data['attach_pid']);
        $insert_data['pid'] = $posthash['pid'];
        if($posthash['posthash'])
        {
            $insert_data['posthash'] = $posthash['posthash'];
        }
        else
        {
            $insert_data['posthash'] = md5($posthash['tid'].$posthash['uid'].random_str());
        }
[...]
        $insert_data['posthash'] = $data['attach_post_key'];
```

Moreover I think it is better to generate the posthash on importing the posts.

http://dev.mybb.com/issues/1402

**Comment by JN-Jones** [comment]
This affects IPB 3 too

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.
