### ISSUE TITLE
Soft Deleted users

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#165]
Vanilla has a column `Deleted` for users which seems to be used for soft deleting user (to be confirmed) so the question is: how do we handle those users? Either skip the user and delete it or ban him?

**Comment by JN-Jones** [comment]
Note: this may apply to other boards too, forgot to take a look there

**Comment by euantorano** [comment]
I'd say just skip the user and don't import.

**Comment by Sama34** [comment]
Since we do not support anything of the sort yes, skip them.
