### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#167]
As mentioned on slack: The code needs to be cleaned up. There are quite a lot of places where we define a variable but never use it or use a variable that's never used. Same for functions. Also sometimes functions are added to the wrong class. A lot of php doc blocks are wrong. Developing the merge system with an IDE doesn't make fun at the moment as you get too many errors.

I heard @euantorano volunteered to fix this?

**Comment by JN-Jones** [comment]
TODO:
- [ ] Make some classes abstract
- [x] Remove closing php tag
- [x] Class output globalizes `$output` 2-times, instead of using `$this`
- [x] Instead of doing `if(method_exists) -> callMethod` the method should be added as empty method to the parent class
- [x] Update file headers, some still say MyBB 1.6
- [ ] Testing

**Comment by euantorano** [comment]
Yes, I'll fix the doc blocks, etc. I'll work on it over this month/next month.

**Comment by JN-Jones** [comment]
You're too late to the party ;)

**Comment by euantorano** [comment]
:(

**Comment by JN-Jones** [comment]
Be happy - it took me more than 4 hours ;)

**Comment by euantorano** [comment]
Ouch. Rather you than me!

**Comment by JN-Jones** [comment]
Ok, hopefully fixed most things now. I'll leave this open for now as I haven't tested it yet.

**Comment by JN-Jones** [comment]
This is finished now
