### ISSUE TITLE
[WBB] Avatars not importet

### ISSUE THREAD

**Issue by MacounDe** [mybb/merge-system#169]
Importing from WoltLab BurningBoard 4.0 to myBB. 
The import runs without errors. But all the Avatars of the users were not imported and are completely missing in myBB. The avatar column of the user table of the myBB database is empty.

**Comment by JN-Jones** [comment]
Avatars aren't merged by the merge system and it never mentions that they will.
https://github.com/mybb/merge-system/issues/140

**Comment by MacounDe** [comment]
Ouch. That's bad.

Thanks for your quick response.
