### ISSUE TITLE
 loginconvert plugin extraneous code & missing remember

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#17]
The loginconvert plugin has a lot of extraneous code. For example, verifying the password just to return to the member login function where the hook was called and validate it again. Also salting a plain md5() password, since once again the standard login functions handle this for us.

Also the remember field introduced in 1.6 is missing from the plugin checks.

http://dev.mybb.com/issues/1292

**Comment by JN-Jones** [comment]
I think the complete plugin could be rewritten - from a quick look there are many unnecessary things.

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment]
I'll close this as I decided to rewrite the plugin to make use of the new login datahandler.
