### ISSUE TITLE
[vB 3.5.x] PM not properly converted

### ISSUE THREAD

**Issue by dprotas** [mybb/merge-system#171]
When merging from a vBulletin 3.5.x database, PMs are not properly converted. The toid and the recipients fields are left blank.

Looking at the code it tries to extract recipients from the cc and bcc nested arrays inside touserarray array. Prior to vB 3.6, those nested arrays didn't exist, recipients were stored directly as id=>username into the touserarray array.

**Comment by JN-Jones** [comment]
I've reverted your PR as we only support the latest version (3.8.8). However as I haven't found any change to `touserarray` in their update script I've modified the foreach to look like the one they use so theoretically this is still fixed.
Also the same applied to vB 4 which still has the extra check.
