### ISSUE TITLE
phpBB import timezone problem

### ISSUE THREAD

**Issue by Stefan-MyBB** [mybb/merge-system#184]
Merge System fails when a user hasn't set a valid timezone:
`Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()`

**Comment by JN-Jones** [comment]
In the latest version? There's a try/catch block around it: https://github.com/mybb/merge-system/commit/d3fc5fd9e47a75b50b53368e891b1ef81000b3f6

**Comment by Stefan-MyBB** [comment]
I guess that fixed it...
