### ISSUE TITLE
Bug Merge Xenforo attachment Module

### ISSUE THREAD

**Issue by TheGameGuard** [mybb/merge-system#186]
Database and table correct I checked .
Posts , Users, Threads all merged but attachments re not importing 

Error Page 
![image](https://cloud.githubusercontent.com/assets/15255639/10680348/77ff78f6-7927-11e5-8505-c061a91e298f.png)

**Comment by JN-Jones** [comment]
Hi,

There was a small spelling mistake in one of the variables which I've fixed now. However please report issues on our forum in the future.

**Comment by Miaourt** [comment]
Same here :'(

**Comment by JN-Jones** [comment]
This is fixed - however as you can see it's in the 1.8.7 milestone so of course it isn't fixed in the latest release. If you want to have a working merge system you need to use the development version but as always we're not giving support for that.

**Comment by Miaourt** [comment]
I think i could give it a try, simply download the repo and i put it in a "merge" folder ?

**Comment by JN-Jones** [comment]
Yeah, just download it and upload it the same way you did with the official package.

**Comment by Miaourt** [comment]
Sorry, I forget to feedback, the master branch worked perfectly, I have merged both xenforo and phpbb3.1 in my new sweet Mybb forum ^^
