### ISSUE TITLE
SQL error if $converted_data['pid'] is empty

### ISSUE THREAD

**Issue by ATofighi** [mybb/merge-system#189]
https://github.com/mybb/merge-system/blob/feature/resources/modules/attachments.php#L287-L292

Reported from: [http://my-bb.ir/Thread-حلشده-انتقال-مطالب-و-پستهای-انجمن-به-انجمن-دیگ](http://my-bb.ir/Thread-حلشده-انتقال-مطالب-و-پستهای-انجمن-به-انجمن-دیگر)

**Comment by JN-Jones** [comment]
Are you sure this isn't a duplicate of #182?
