### ISSUE TITLE
 PunBB Usergroups Error

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#19]
Reference: http://community.mybb.com/thread-107109.html

When no custom usergroups are created the module keeps going while claiming 1 usergroup to import.

http://dev.mybb.com/issues/1767

**Comment by JN-Jones** [comment]
The import query checks for ids > 3 but the first four groups are continued in the loop. Instead we should simply query for ids > 4 and delete the `if` in the loop.

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.
