### ISSUE TITLE
SQL Error xf_attachment

### ISSUE THREAD

**Issue by sc4t** [mybb/merge-system#192]
I have an error with the xenforo converter

MyBB SQL Error
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM xf_attachment' at line 1
Query:
SELECT FROM xf_attachment
Please contact the MyBB Group for technical support.

**Comment by JN-Jones** [comment]
Please use the support forums for support. As said there this is likely a duplicate of #186

**Comment by JN-Jones** [comment]
Closing this as no feedback was provided.
