### ISSUE TITLE
[IPB4] Usernames with polish chars are imported incorrectly

### ISSUE THREAD

**Issue by krzyc** [mybb/merge-system#193]
Usernames with polish chas are imported incorrectly e.g. Bogusław is imported as BogusÅaw. Other fields as far as I know are imported correctly.

It is probably caused by encode_to_utf8 method.

**Disabling UTF-8 conversion in merge configuration fixes the problem.**

**Comment by JN-Jones** [comment]
Seems to be fixed then.
