### ISSUE TITLE
 SMF1 & SMF2 timeformat import not correct

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#20]
SMF stores time format in the db as:
%B %d, %Y, %I:%M:%S %p

And we'll need to convert these to the equivalent MyBB number codes for the time format.

http://dev.mybb.com/issues/1687

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.
