### ISSUE TITLE
[VB3] threads & posts warnings with php 7.X

### ISSUE THREAD

**Issue by andrewjs18** [mybb/merge-system#201]
when importing threads:
![031 02 59](https://cloud.githubusercontent.com/assets/2748980/24284506/fd51779a-1041-11e7-8722-8fbecbfb7995.jpg)

when importing posts:
![032 03 02](https://cloud.githubusercontent.com/assets/2748980/24284509/053991fe-1042-11e7-8d38-08297ac01182.jpg)

**Comment by yuliu** [comment]
The fix was merged in #191.
