### ISSUE TITLE
 MyBB 1.6 to MyBB 1.6 - Last Post Wrong

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#21]
I tried importing my current MyBB 1.6 forum to a new installation, and the Last Post section does not update. By that, I mean the links to the thread URL and the username does not update, thus leading to a 404 error.

ie. It should be linking to showthread.php?tid=12345 but is linking to tid=12354 like in the old forum.

Might also be because I purged a few things before merging, so it may be my fault

http://dev.mybb.com/issues/1643

**Comment by JN-Jones** [comment]
Duplicate: #31
