### ISSUE TITLE
Issues merging into MyBB 1.8.16+

### ISSUE THREAD

**Issue by euantorano** [mybb/merge-system#210]
https://community.mybb.com/thread-218590.html

These issues are caused by the removal of some contact fields such as AIM in 1.8.16, and stop merges working at all.

**Comment by AndreRl** [comment]
This has been an issue as of late. What would be the preferred way of handling this? Temporarily putting the `aim` field back for the merge and warning users that the said data will be removed due to aim no longer being supported? Or creating a separate mybb_users table structure for 1.8.16+? @euantorano

**Comment by ErikThiart** [comment]
This is still an issue

```
MyBB SQL Error
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1054 - Unknown column 'aim' in 'field list'
```

**Comment by yuliu** [comment]
> This is still an issue
> 
> ```
> MyBB SQL Error
> MyBB has experienced an internal SQL error and cannot continue.
> 
> SQL Error:
> 1054 - Unknown column 'aim' in 'field list'
> ```

Could you please elaborate on the version of merge system and the boards and versions of source and target boards respectively?

**Comment by ErikThiart** [comment]
@yuliu sure,

I installed MyBB (fresh install) 1.8.22 - I downloaded it from the official website.

I then downloaded and installed the MyBB Merge System version 1.8.11 from here (https://mybb.com/download/merge-system/)

I then attempted to import phpBB version 3.3.0 and got the error above, amongst others.

I then added `aim` to the MyBB user table and then got the same error, but for `yahoo` which I then also added and then it worked.

So managed to get around it, but yes might need to add this to the official docs somewhere or create some kind of conditional statement to add those columns to the MyBB users table if detected on phpBB.

**Comment by yuliu** [comment]
@ErikThiart oh, the version at https://mybb.com/download/merge-system/ is a bit old and doesn't have recent updates in GitHub.
Please try again using the merge system from here, this repository. Download it as a .zip file: https://github.com/mybb/merge-system/archive/feature.zip

**Comment by ErikThiart** [comment]
@yuliu how does the installation work for this one, so I just copy it to the MyBB installation folder and navigate to boardurl.com/merge-system-feature/ or do I rename it to merge?

**Comment by yuliu** [comment]
> @yuliu how does the installation work for this one, so I just copy it to the MyBB installation folder and navigate to boardurl.com/merge-system-feature/ or do I rename it to merge?

Yes you could rename the extracted folder `merge-system-feature` to `merge` and upload/move it to the forum root, then visit boardurl.com/merge/ in web browser.

For questions about using the merge system it's better to post in its support forum at https://community.mybb.com/forum-180.html

**Comment by ErikThiart** [comment]
Much appreciated!

Unfortunately, I think I am banned there for causing to much flack pointing out a lack of communication and direction. 

I just need MyBB till the end of the year then moving to xenforo

That said, your help as been fantastic - they should pay you.

**Comment by euantorano** [comment]
We still need to release a new version of the merge system, we should probably do that after 1.8.23 is released, pinging @mybb/developers as a reminder.

**Comment by StarredSkies** [comment]
I am upgrading from SMF 2.0 and this appears to be an issue with MyBB 1.8.37. How was this resolved in previous versions? I would like to fix this.

`MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1054 - Unknown column 'id_msg' in 'where clause'`

[This appeared to be an issue previously](https://github.com/mybb/merge-system/issues/210) but it has come back up. 

[See thread on MyBB community.](https://community.mybb.com/thread-239963.html)
