### ISSUE TITLE
Post and Thread visibility error

### ISSUE THREAD

**Issue by kat-kta** [mybb/merge-system#211]
The merge system when merging an old mybb database with a freshly installed new one, changes visibility of all posts and threads to a positive number, so all drafts (visibility -2) and deleted posts (visitbility -1) are suddenly visibility 9 which makes them searchable and counted in the profiles.

**Comment by yuliu** [comment]
Fix was merged in https://github.com/mybb/merge-system/commit/b3d1540f6ea63d6a3a6d19b0dd6bed462b7f3254#diff-445c5be011e7f33ed43d44f4a088a5c7
