### ISSUE TITLE
Development runs again?

### ISSUE THREAD

**Issue by burner1024** [mybb/merge-system#216]
I understand that since 2.0 itself is [put on hold itself](https://blog.mybb.com/2018/06/28/mybb-2-0-is-being-put-on-hold/), the note about development stop in the readme is no longer relevant?

**Comment by euantorano** [comment]
Yeah, it’s not particularly relevant, though we do still plan to eventually rewrite the merge system when we have enough resources to do so.

**Comment by yuliu** [comment]
Yes and we'll try to keep the merge system updated with MyBB's release.
