### ISSUE TITLE
Bans aren't transferred from PHPBB3

### ISSUE THREAD

**Issue by burner1024** [mybb/merge-system#217]
As far as I can see, there's no code to handle that at all, so I guess this is a feature request.

**Comment by veryard** [comment]
I'm happy to write the code for this but looks like development for this branch has stopped?

**Comment by euantorano** [comment]
Development hasn’t stopped, but the team member who used to contribute the most code to this project left the team a while back and nobody else has really picked it up. 

Our longer term goal is a full rewrite and rethink of the merge system, but we are certainly happy to accept patches for the current version.

**Comment by veryard** [comment]
Thanks @euantorano 

It looks to me like bans where not included in of the boards, I made a pull request, might need some additional testing. I wrote the bans module class etc.

https://github.com/mybb/merge-system/pull/220

Thanks,
Brad.

**Comment by euantorano** [comment]
Awesome, thanks @veryard!
