### ISSUE TITLE
PHPBB 3.2: posts contain html

### ISSUE THREAD

**Issue by burner1024** [mybb/merge-system#218]
After migration, posts appear to be filled with HTML tags.
Reason and a workaround detailed [here](https://community.mybb.com/thread-208481-post-1322935.html).

![0SKV7Wp](https://user-images.githubusercontent.com/1279852/54807577-3ba2f080-4cb0-11e9-9e04-3d1126e78f9f.png)

**Comment by veryard** [comment]
- Edit

My bad, didn't see the link you provided, i'll have a look and make a pull request.

Thanks,
Brad.

**Comment by veryard** [comment]
Have made a pull request that fixes this.

![image](https://user-images.githubusercontent.com/3941758/54879766-c2ee9080-4e77-11e9-9f4d-514090274bf8.png)


Thanks,
Brad.

**Comment by veryard** [comment]
Can this be closed? @euantorano 

Thanks.

**Comment by euantorano** [comment]
Yep, will close now - thanks!
