### ISSUE TITLE
 SMF 1 - Module forum permissions: wrong count of the items to be imported

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#22]
Hi,

the Forum Permissions module of the SMF 1 merge system do not count correctly the items to be imported.
In fact, the query count do not respect the same conditions of the select query used for the real import (ignoring the GROUP BY ID_GROUP, ID_BOARD condition), so the merge will loop infinitely when the real count is lesser than the one performed.
See the queries at lines 42 and 117 of the boards/smf/forumperms.php

To resolve the problem this is a possible patch:

=== modified file 'boards/smf/forumperms.php'
--- boards/smf/forumperms.php    2011-06-29 21:56:30 +0000
+++ boards/smf/forumperms.php    2011-06-30 13:30:49 +0000
@@ -114,8 +114,8 @@
         // Get number of forum permissions
         if(!isset($import_session['total_forumperms']))
         {
-            $query = $this->old_db->simple_select("board_permissions", "COUNT(*) as count", "ID_GROUP != '-1' AND ID_BOARD > 0");
-            $import_session['total_forumperms'] = $this->old_db->fetch_field($query, 'count');
-            $query = $this->old_db->simple_select("board_permissions", "1", "ID_GROUP != '-1' AND ID_BOARD > 0 GROUP BY ID_GROUP, ID_BOARD ");
-            $import_session['total_forumperms'] = $this->old_db->num_rows($query);
           $this->old_db->free_result($query);
       }

Another way to achieve the same result is to made a subselect.

http://dev.mybb.com/issues/1618

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.
