### ISSUE TITLE
XenForo 2.0/2.1 Merge Module

### ISSUE THREAD

**Issue by euantorano** [mybb/merge-system#234]
We need a merge module for XenForo 2.0/2.1. I've not yet evaluated what differences there are in database structure between 1.x and 2.x.

I have an XF2 license to get sample data out of to test the merge process.

**Comment by yuliu** [comment]
~~**Note:** XenForo 2 uses `utf8mb4` for MySQL's encoding, the UTF-8 conversion should be unchecked.~~

**Note:** Forums upgraded from XF 1 may still use `utf8` as MySQL tables' encoding, but XenForo 2 uses `utf8mb4` by default. So, it's better to install MyBB in `utf8mb4` encoding in MySQL. Have no idea what's the equivalent to PostgreSQL & SQLite.

**Comment by veryard** [comment]
Am happy to work on this over the coming weekend.
