### ISSUE TITLE
`yahoo` contact field discontinued

### ISSUE THREAD

**Issue by yuliu** [mybb/merge-system#240]
IIRC, @euantorano mentioned in Discord that merge system will have a new release?

As a reminder and as a note here:
 - Code base from https://github.com/mybb/merge-system/commit/9a36efa08fd5e03fcc5e5d737e5b722de023ff02 and later will apply for MyBB version from 1.8.16 to 1.8.21 ([column `aim` in table `users` is dropped](https://github.com/mybb/mybb/blob/mybb_1816/install/resources/upgrade43.php#L39)), until the drop of `yahoo` support in `import_users`.
 - Code base before that should apply for MyBB 1.8.15 and earlier version to 1.8.11 (at least maybe, listed in the [merge download page](https://mybb.com/download/merge-system/)).
 - After MyBB 1.8.22's release, the merge system should drop support of `yahoo` in `import_users`, as per [change here](https://github.com/mybb/mybb/blob/mybb_1822_build/install/resources/upgrade49.php#L33).

**Comment by euantorano** [comment]
Yep, it’s still planned to release a new version. I’m not sure if we have a packaging tool for it like we do the core, but if not we will need to document the process at least.
