### ISSUE TITLE
 Avatars from SMF & SMF2 attachments tables aren't being ignored

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#25]
Since these have ID_MSG (smf1.1)/id_msg (smf 2) set to 0 for avatars, we need to make the Merge System ignore anything in the attachments table with 0 for the msg... double checking needs to be done that all 0s are in fact avatars, but this seems to be borne out by both my test boards.

http://dev.mybb.com/issues/1265

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment]
Fixed with #136
