### ISSUE TITLE
 mime_content_type has been deprecated

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#26]
Since mime_content_type() has been deprecated and replaced by the PECL extension Fileinfo() we should update the code to test for it, use it if available, if not test for Fileinfo(), use it if available, and if not use our current fallback. Or possibly do Fileinfo, fallback to mime_content_type, then fallback to our current fallback.

http://dev.mybb.com/issues/1250

**Comment by nmalcolm** [comment]
This seems to be correct. I haven't been able to test it out though.

@Polarbear541 @ccalby @ImadJomaa @JN-Jones

**Comment by ImadJomaa** [comment]
Looks right. I'll go ahead and test your changes to smf - didn't see any other commits to other boards that are affected by it.

**Comment by nmalcolm** [comment]
I couldn't find any other calls to mime_content_type()...

https://github.com/mybb/MyBB-Merge/search?q=mime_content_type

**Comment by JN-Jones** [comment]
I'll close this as I can't see any issues. @ImadJomaa: If you've found any issues reopen the issue.
