### ISSUE TITLE
How to donate to help with the merge development

### ISSUE THREAD

**Issue by luisalvarado** [mybb/merge-system#262]
Hi merge team, I have 2 clients that want to leave vanilla and migrate to mybb and I have explained to them what mybb is, how it works and the benefits of using it, but I also explained that the merge is not yet finished for Vanilla. Is there a way for me to donate in order to accelerate development of it. I can also provide example SQL file exactly how vanilla gives them to our clients.

**Comment by euantorano** [comment]
Example SQL files with data from Vanilla would be a big help - we can easily get data for the free version of Vanilla but I believe the cloud hosted version is a little bit different?

If you can email me them to “euantor -at- mybb.com” then I’ll try and have a look at them over this weekend and see what I can do.

**Comment by luisalvarado** [comment]
Oh sorry @euantorano just noticing the message. Sending it over right now to you.

**Comment by euantorano** [comment]
Yep, received. Thanks very much!
