### ISSUE TITLE
Vanilla import: PM import warning - invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by euantorano** [mybb/merge-system#268]
When importing PMs in the Vanilla forum module, the following warnings are shown:

<img width="1904" alt="Screenshot 2021-01-24 at 17 03 02" src="https://user-images.githubusercontent.com/748913/105637553-14964680-5e66-11eb-86ee-2f2e13f52457.png">

**Comment by euantorano** [comment]
Note: this relates to the following block of code:

https://github.com/mybb/merge-system/blob/feature/boards/vanilla/privatemessages.php#L45:L48

The format of the `recips` column in the data I have is as follows:

```
a:3:{i:0;s:1:"2";i:1;s:1:"4";i:2;s:2:"12";}
```

**Comment by luisalvarado** [comment]
Thank you buddy, awesome news here. How can I test this.

**Comment by euantorano** [comment]
> Thank you buddy, awesome news here. How can I test this.

At the moment, I don't have a proper fix in place - as these are just warnings, the merge system continues and simply doesn't import PMs. That's obviously not ideal though. I need to retry this and work out a fix, I suspect it's not a problem happening for every single PM, but rather just some of them.
