### ISSUE TITLE
Vanilla import: warning importing avatars when AWS S3 is used for storage

### ISSUE THREAD

**Issue by euantorano** [mybb/merge-system#269]
When AWS S3 is used for avatar storage, the avatar import module for Vanilla throws the following warnings:

<img width="1904" alt="Screenshot 2021-01-24 at 17 07 52" src="https://user-images.githubusercontent.com/748913/105637744-e1a08280-5e66-11eb-91b8-8ae7054e9f58.png">

This is due to S3 uploads having the form `s3://uploads/userpics/...`.

**Comment by luisalvarado** [comment]
Awesome news yesss!!! Thank you buddy. So how is this fixed?

**Comment by euantorano** [comment]
> Awesome news yesss!!! Thank you buddy. So how is this fixed?

There are 2 options - one of which is easy, the other not so easy:

1. Ignore avatars as part of the merge that have `s3://` at the start (this is the easy option, but not ideal).
2. Add a step that runs before the merge that downloads all avatars from S3 to a local folder. This will require some additional details like S3 URL and such to work (this is the harder option, but could be done manually outside of the merge system with a bash script, which would be my preference short term).

**Comment by luisalvarado** [comment]
Could the other Vanilla issues be merged without this one, so we could start testing with our data site?

**Comment by euantorano** [comment]
Sure, that sounds like a good compromise. I'll try get that done ASAP and get a demo up for you.

**Comment by luisalvarado** [comment]
> Sure, that sounds like a good compromise. I'll try get that done ASAP and get a demo up for you.

please thank you Euan. We do not worry about the images since we could maybe create an API that can handle that later one, everything else that you have worked on has so much value for the import process to go smoothly and avoid the bullying from Vanilla.

Thank you buddy.

**Comment by luisalvarado** [comment]
Hi buddy any updates @euantorano
