### ISSUE TITLE
 Posts not restored for phpBB2 threads with the same title

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#27]
If there are two threads with the exact same name, for example as a result of a move from forum to forum, where the other thread is a simple shadow/redirection, the thread posts and details such as "dateline" are NOT merged.

In the database mybb_threads table you can find only one row for the threads, which has only the topic title & view count, everything else is 0.
To reproduce:

```
Install phpBB2
Create a new forum
Move the only thread to the newly created forum, leave a shadow topic about the move
Use Merge System
```

http://dev.mybb.com/issues/1244

**Comment by JN-Jones** [comment]
As we don't support phpBB 2 anymore and I can't remember that I've ever seen this bug with phpBB 3, I'll close this.
