### ISSUE TITLE
 importing users throws up a warning

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#28]
File Line Function
/convert/boards/smf.php 115 errorHandler->error
/convert/boards/smf/users.php 87 SMF_Converter->get_group_id
/convert/resources/modules/users.php 123 SMF_Converter_Module_Users->convert_data
/convert/boards/smf/users.php 69 Converter_Module_Users->insert
/convert/index.php 970 SMF_Converter_Module_Users->import
Warning [2] Invalid argument supplied for foreach() - Line: 115 - File: convert/boards/smf.php PHP 5.3.2-1ubuntu4.5 (Linux)

I get this for every user being imported.
Users stage shows "completed" afterwards though and I can continue with the conversion process.
I used the merge system from the main site (no trunk files).

http://dev.mybb.com/issues/1238

**Comment by JovanJ** [comment]
No such error for me. 
Seems like this is fixed also, anyone else?

**Comment by JN-Jones** [comment]
Not sure but probably the following code should be changed:

``` php
        if(!is_numeric($group_id))
        {
            $groups = $group_id;
        }
        else
        {
            $groups = array($group_id);
        }
```

to:

``` php
        if(is_array($group_id))
        {
            $groups = $group_id;
        }
        else
        {
            $groups = array((int)$group_id);
        }
```

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment]
I was able to reproduce this with an example database, my fix above worked so I'll create a PR later today.
