### ISSUE TITLE
Help to merge SMF 2.0.19 ??

### ISSUE THREAD

**Issue by GodOfWareFare** [mybb/merge-system#294]
Hi am very new in the whole process,can someone please explain to me this--> do i have to upload the merge directory on my SMF forum root directory or do i need to make a subdirectory and upload merge directory there? lets say my SMF forum is https://myforum/
sould is upload it here https://myforum/merge? or sould i make a new directory lets say https://myforum/forum/merge?and one more thing,do i need to upload also the mybb installation files to the same directory where merge is?Or just the merge system?I am so confused,please any help?

**Comment by Stefan-MyBB** [comment]
For support please use the community forums: https://community.mybb.com/forum-180.html

**Comment by GodOfWareFare** [comment]
I did but still waiting for answer!

**Comment by yuliu** [comment]
Make sure you have the complete MyBB installed and Merge system uploaded.

Ref: https://docs.mybb.com/1.8/merge/running/#uploading-the-files

> Uploading the Files
> With the files extracted from the MyBB package, upload the ‘merge’ directory from the package to your existing installation of MyBB’s folder. You must keep the files inside the ‘merge’ directory.

As Stefan said, please use the forum for support. Closing it.
