### ISSUE TITLE
 Users Table Warnings

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#3]
When merging users, the warningpoints column should either be set to 0 or the mybb_warnings table should be merged in.

http://dev.mybb.com/issues/2263

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment]
All issues are old ones (old merge system version and old merge board version). And all need to be tested. So instead of commenting you could test them and set the label or reject them :P

**Comment by JordanMussi** [comment]
Fair point. :wink:

**Comment by JN-Jones** [comment]
This has been fixed with my changes to the `prepare_insert_array`.
