### ISSUE TITLE
Counters/Links not updated

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#31]
Upon merging a database, I discovered a bug with the "Last Post" link. Instead of taking you to the last post, it returns with a "The Specified Thread Does Not Exist" message, as it tries to go to a different thread link.

Example:

Click on the "Posts?" link in the first catergory.
It will go to http://dotrb.net/thread-603-lastpost.html
And then it will say:

The specified thread does not exist.

But then going to the normal thread via navigation it will take you to:
http://dotrb.net/thread-595.html

The above issue was fixed, as the links will work correctly now. It was just an example.

As instructed by Dylan Myers, we found that running a Recount and Rebuild fixes the error.

http://dev.mybb.com/issues/1158

**Comment by JN-Jones** [comment]
This issue occurs with all softwares we support. While Recount and Rebuild works, we should do this automatically (probably run "Recount and Rebuild" in the cleanup module?)

**Comment by JN-Jones** [comment]
Postpointing, for now the docs should say "Use r&r"

**Comment by JN-Jones** [comment]
This has been started in a seperate branch too.

**Comment by JN-Jones** [comment]
This should be finished now. I can't test it atm with bigger boards therefore I'll keep this open till I do so.

**Comment by JN-Jones** [comment]
Tested with several boards and couldn't find any issues.
