### ISSUE TITLE
Birthdays are wrong after import from vB 3.8.4

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#32]
I just made an testimport from an vB-Forum and the birthdates got all mixed up.

The day gets the number of the month and the month keeps beeing empty.

For example: "December 2nd 1970" from vB becomes "(no month) 12th 1970" in MyBB.

http://dev.mybb.com/issues/566

**Comment by JovanJ** [comment]
Tested on big board, and every user birthday is successfully converted. Did someone else tested it?

**Comment by LakesGeek** [comment]
I have this issue as well.  Both systems use a varchar for the birthday, but while vB uses the American mm-dd-yyyy format, MyBB uses the British dd-mm-yyyy instead.  It's a direct field to field translation, so the date and month get swapped.

Not sure how to fix this in the code.  A bit of SQL trickery should fix it in the tables afterwards.  I only have a very small board so I just fixed people's birthdays manually.

**Comment by JN-Jones** [comment]
We don't support vB 3 anymore, but we should check whether this affect vB 4 too.

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by ghost** [comment]
I don't have a license for vB4 so I can't fully verify but the code that was the issue in vB3 is directly copied in the vB4 user merge module on your development branch for 1.8.  Based on that it seems highly likely it is also a problem there.

**Comment by JN-Jones** [comment]
I was able to reproduce and fix it.
