### ISSUE TITLE
SMF 2 attachments convert error

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#34]
1054 - Unknown column 'attachment_type' in 'where clause'

attachment_type column doesen't exists in attachment smf table.

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment]
I'm not able to reproduce this, `attachment_type` exists in my test databases.

**Comment by JN-Jones** [comment]
@JovanJ? Otherwise I'll close this.
