### ISSUE TITLE
Error when trying to convert threads SMF 2

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#35]
Error:

 1054 - Unknown column 'id_msg' in 'where clause'

id_msg column exists in messages table but, something else is the problem. I am still not sure what is it.

**Comment by JovanJ** [comment]
Tested and seems like it's fixed. Someone confirm?

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment]
I wasn't able to reproduce it and didn't found any line where this might happen.
