### ISSUE TITLE
Error when trying to convert settings SMF 2

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#36]
Error:

```
1054 - Unknown column 'variable' in 'where clause'
```

Just noticed this error, I wasn't able to take a look over the code and see what is happening.

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment]
I'm not able to reproduce this, the settings table has a column `variable`

**Comment by JN-Jones** [comment]
@JovanJ? Otherwise I'll close this.
