### ISSUE TITLE
vBulletin permissions SQL error

### ISSUE THREAD

**Issue by PenguinPaul** [mybb/merge-system#43]
http://community.mybb.com/thread-151023.html

**Comment by nmalcolm** [comment]
Have you checked this is the same for vB 3.6, 3.7 and 3.8?

Additionally fixes should be pushed to feature too.

**Comment by PenguinPaul** [comment]
I don't have an available database but I'd assume if they have decent development they wouldn't change a database field name based on an 's'.  First time pushing for merge system so I didn't realize there were several branches.

**Comment by nmalcolm** [comment]
This needs more research, I'm not entirely happy with an assumption that they're doing things correctly. There have been many successful conversions from vB to MyBB so if this is specific to vB 3.8 then it's going to break for 3.6/3.7 conversions.

**Comment by JN-Jones** [comment]
I'll close this for now as the issue was already reported more than two years ago. This is also related to [this internal thread](http://community.mybb.com/thread-154793.html).
