### ISSUE TITLE
Forum Permissions module for SMF 2 redirects infinitely

### ISSUE THREAD

**Issue by Starpaul20** [mybb/merge-system#44]
When you run the Forum Permissions module for SMF 2 it will redirect infinitely.

**Comment by JovanJ** [comment]
There is also one more issues regarding Forum Permissions:

https://github.com/mybb/merge-system/issues/11

Probably it requires, to be rewriten.

**Comment by JN-Jones** [comment]
It needs a rewrite. Even after fixing #47 I wasn't able to exactly locate the issue - still testing.

**Comment by Sama34** [comment]
This doesn't happens to me so I will assume it is fixed?

**Comment by JN-Jones** [comment]
The forumpermissions module wasn't working and depending on the smf settings different errors occured.
