### ISSUE TITLE
SMF 2 Poll Votes not converted properly

### ISSUE THREAD

**Issue by Starpaul20** [mybb/merge-system#45]
Poll Votes converted from SMF 2 are not converted properly.

Poll votes are not attached to the poll they belong to (pid in pollvotes table is set to 0).

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by Starpaul20** [comment]
Looks like it does.
