### ISSUE TITLE
Forumpermissions module not working

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#47]
There's some wrong logic in the forumpermissions module. We don't copy the default usergroups (registered, admin, mod, smod) but we try to copy their forum permissions. We have an array with "old_id => new_id" in the cache but the default groups aren't cached their so it produces some SQL errors when the default groups have their own permissions (tested on a fresh SMF installation and on a phpBB 3 installation, where you first need to set some permission)

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.
