### ISSUE TITLE
trackers - table vs columns

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#68]
We have two trackers tables (post and private message) but in all other tables we simply add the tracker columns to the main table (eg users). We should stick with one method. I'd prefer the second one as it's easier then to query additional infos in one go.
@JovanJ @PirataNervo

**Comment by JN-Jones** [comment]
Postpointing

**Comment by JN-Jones** [comment]
Whoever checks this (yeah, likely me again) should also check whether we really need the tracker. Eg we never need the `import_pmid` one as none of the other modules uses it. Same for the usergroup trackers, as the usergroup module needs to be run before the users module the users module already updates the usergroups and (afaik) none of the other modules needs the old ids.

**Comment by Sama34** [comment]
Plugins can make use of that data during or after the merge is complete, don't you agree?

**Comment by JN-Jones** [comment]
There isn't any plugin system in the merge system (that'd be funny - it's already more than complicated and nobody wants to work on it, imagine considering plugins destroying everything). And trackers are removed after the merge as there isn't any need of them later.
