### ISSUE TITLE
 phpBB3: merging avatars is not implemented (patch included)

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#7]
phpBB3: merging avatars is not implemented

(I've tried to attach the patch here, but there seems to be a
configuration error. So it's here instead:)

http://mark13.org/0001-phpBB3-merge-avatars.patch

http://dev.mybb.com/issues/2072

**Comment by JordanMussi** [comment]
Does this apply to 1.8? As the 1.6 Merge System will receive no more updates keeping a 1.6-specific issue on the tracker is unnecessary.

**Comment by JN-Jones** [comment]
This has been replaced by #140
