### ISSUE TITLE
 PHPBB3 : Additional User groups are wrong

### ISSUE THREAD

**Issue by JovanJ** [mybb/merge-system#9]
Hello. I tried to convert vbulletin 3.6.8 forums to mybb 1.6.5, but I got many problems... Only few features worked (marked on screenshot).
Blank page = white page without title or anything else (I tried to F5 but still nothing)
SQL error when converting forum permissions:
[URL=http://imageshack.us/photo/my-images/513/sql.png/][IMG]http://img513.imageshack.us/img513/3618/sql.th.png[/IMG][/URL]

And whole list of broken features:
[URL=http://imageshack.us/photo/my-images/515/mybbmergesystemmodulese.png/][IMG]http://img515.imageshack.us/img515/3686/mybbmergesystemmodulese.th.png[/IMG][/URL]

http://dev.mybb.com/issues/1861

**Comment by ghost** [comment]
Issues with this issue. Either title is wrong or the content is wrong. Redmine link based on title is http://dev.mybb.com/issues/1981 and I have fixed that per the link in 1981

**Comment by JovanJ** [comment]
Ah, my bad them. I'll close this issue then :) Thanks pavemen! If you find something similar, feel free to comment again or PM me on community.
