### ISSUE TITLE
vBulletin private message merge not setting folder for items in inbox

### ISSUE THREAD

**Issue by ghost** [mybb/merge-system#94]
I can only verify this on vBulletin 3.8.x but looking at the code on the feature branch I suspect this same issue impacts 4.x.

The issue is in the privatemessages merge module when it is setting the folder field of the insert_data object it only evaluates folderid == -1.

There is an entirely separate issue when users have custom private message folders but at a minimum it should at least check for folderid == 0 which is the ID for the vBulletin inbox.

**Comment by JN-Jones** [comment]
The vB4 module needs to be fixed anyways, it's still a beta one.
@JovanJ I assign this to you.

BTW: we don't support vB3 anymore.

**Comment by ghost** [comment]
I understand vB3 isn't supported anymore which is why I'll make that fix in my own fork since I need it and perhaps some others still do as well.

I've found another issue in the vB3 merge code related to setting of PM subjects.  Again I can't confirm it impacts vB4 but I suspect it does.  Given that you don't support vB3 and I can't confirm it impacts vB4 should I still go ahead and create the issue?

**Comment by JN-Jones** [comment]
So in MyBB 0 and 1 are Inbox and 2 is Outbox.
vB uses 0 as Inbox and -1 as Outbox?

I'll check the pm subject thing later.

**Comment by JN-Jones** [comment]
I've fixed the pm subject part. @annatar if you're confirming the folder ID's I posted above I'll fix that too.

**Comment by ghost** [comment]
That is correct at least for vB3.x.  That is the only license I have I have to test against.  Knowing their development patterns I highly doubt they changed it for vB4/5.

**Comment by JN-Jones** [comment]
But then the code is correct isn't it? (Changed 0 to 1 as we're using that everywhere else but that shouldn't matter much)

``` php
        if($data['folderid'] == -1)
        {
            // Outbox
            $insert_data['folder'] = 2;
        }
        else
        {
            // Inbox
            $insert_data['folder'] = 1;
        }
```

**Comment by ghost** [comment]
If you are saying that both folder zero and one are seen as the 'inbox' by the MyBB code then it seems like it is correct.

When I did a test conversion it didn't seem to display anything in my inbox but it may have been more of a side effect of the PM subject issue.

I'm not sure how the MyBB code behaves if it finds a PM with no subject set.

**Comment by JN-Jones** [comment]
Hmm, seems to work for me with my test database. We will see whether it works :P
