### ISSUE TITLE
Private Message module

### ISSUE THREAD

**Issue by JN-Jones** [mybb/merge-system#97]
While we save multiple copies of the pm (one for the author, and one for every recipient) others don't do that. The merge system should handle that.

Steps to reproduce (on phpBB):
Send PM from T1 -> T2
Merge
Afterwards only T2 can see the PM, it's lost for T1.

**Comment by JovanJ** [comment]
We should first merge one for author, and after that to all recipients. Otherwise, it can be a bit confusing what is happening.

**Comment by JN-Jones** [comment]
Note that some modules don't need it (eg mybb -> mybb)

**Comment by JN-Jones** [comment]
All modules merge now a copy per user so every user participated in a conversation/pm gets his copy now. However there are some options/settings to test:
- Answered has a special status. If the merge board has that status too (or it's easily testable) we should properly set it. If we would need to some SQL magic we can ignore it
- Same for forwarded messages (not supported by all modules)
- Deleted messages aren't considered at all (trash)
- Same for drafts
- Conversations have some special options, eg a conversation can be started, one user lefts but the rest send more messages. Atm those things are ignored which can leak informations.
- Some boards have a `saveInOutbox` setting which should be considered too.

**Comment by JN-Jones** [comment]
Only WBB 3 & 4 and XenForo are missing.

**Comment by JN-Jones** [comment]
This is finally fixed.
